-- MySQL Script generated by MySQL Workbench
-- Sat May 28 13:42:25 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`DZ4_UlogaKorisnika`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DZ4_UlogaKorisnika` (
  `idDZ4_UlogaKorisnika` INT NOT NULL,
  `Uloga` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idDZ4_UlogaKorisnika`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Kolacici`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Kolacici` (
  `idKolacici` INT NOT NULL,
  `Tip kolacica` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idKolacici`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DZ4_Korisnik`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DZ4_Korisnik` (
  `idKorisnik` INT NOT NULL,
  `Ime` VARCHAR(45) NOT NULL,
  `Prezime` VARCHAR(45) NOT NULL,
  `Godina_rodenja` DATE NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Korisnicko ime` VARCHAR(45) NOT NULL,
  `Lozinka` VARCHAR(45) NOT NULL,
  `PotvrdaLozinke` VARCHAR(45) NOT NULL,
  `DZ4_UlogaKorisnika_idDZ4_UlogaKorisnika` INT NOT NULL,
  `Kolacici_idKolacici` INT NOT NULL,
  PRIMARY KEY (`idKorisnik`),
  INDEX `fk_DZ4_Korisnik_DZ4_UlogaKorisnika_idx` (`DZ4_UlogaKorisnika_idDZ4_UlogaKorisnika` ASC),
  INDEX `fk_DZ4_Korisnik_Kolacici1_idx` (`Kolacici_idKolacici` ASC),
  CONSTRAINT `fk_DZ4_Korisnik_DZ4_UlogaKorisnika`
    FOREIGN KEY (`DZ4_UlogaKorisnika_idDZ4_UlogaKorisnika`)
    REFERENCES `mydb`.`DZ4_UlogaKorisnika` (`idDZ4_UlogaKorisnika`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DZ4_Korisnik_Kolacici1`
    FOREIGN KEY (`Kolacici_idKolacici`)
    REFERENCES `mydb`.`Kolacici` (`idKolacici`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Novi_sadrzaj`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Novi_sadrzaj` (
  `idNovi_sadrzaj` INT NOT NULL,
  `File` VARCHAR(45) NOT NULL,
  `Kategorija` VARCHAR(45) NOT NULL,
  `Vrijeme_kreiranja` DATETIME NOT NULL,
  `Opis` VARCHAR(255) NOT NULL,
  `Mjesec` DATE NOT NULL,
  `Boja` VARCHAR(45) NOT NULL,
  `Mobitel` VARCHAR(45) NOT NULL,
  `DZ4_Korisnik_idKorisnik` INT NOT NULL,
  PRIMARY KEY (`idNovi_sadrzaj`),
  INDEX `fk_Novi_sadrzaj_DZ4_Korisnik1_idx` (`DZ4_Korisnik_idKorisnik` ASC),
  CONSTRAINT `fk_Novi_sadrzaj_DZ4_Korisnik1`
    FOREIGN KEY (`DZ4_Korisnik_idKorisnik`)
    REFERENCES `mydb`.`DZ4_Korisnik` (`idKorisnik`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
