-- MySQL Script generated by MySQL Workbench
-- Sun Apr 10 11:03:10 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema WebDiP2021x001
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema WebDiP2021x001
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `WebDiP2021x001` DEFAULT CHARACTER SET utf8 ;
USE `WebDiP2021x001` ;

-- -----------------------------------------------------
-- Table `WebDiP2021x001`.`tip_korisnika`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WebDiP2021x001`.`tip_korisnika` (
  `idtip_korisnika` INT NOT NULL,
  `tip_korisnika_naziv` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idtip_korisnika`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WebDiP2021x001`.`racun`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WebDiP2021x001`.`racun` (
  `idracun` INT NOT NULL,
  `racun_stavke` VARCHAR(45) NOT NULL,
  `racun_iznos` VARCHAR(45) NOT NULL,
  `racun_status` TINYINT NOT NULL,
  `racun_datum` DATETIME NOT NULL,
  PRIMARY KEY (`idracun`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WebDiP2021x001`.`korisnik`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WebDiP2021x001`.`korisnik` (
  `idkorisnik` INT NOT NULL,
  `korisnik_ime` VARCHAR(45) NOT NULL,
  `korisnik_prezime` VARCHAR(45) NOT NULL,
  `korisnik_korisnicko_ime` VARCHAR(45) NOT NULL,
  `korisnik_lozinka` VARCHAR(45) NOT NULL,
  `korisnik_email` VARCHAR(45) NOT NULL,
  `korisnik_datum_pristupanja` DATETIME NOT NULL,
  `korisnik_datum_zabrane` DATETIME NOT NULL,
  `korisnik_datum_prihvacanja_kolacica` DATETIME NOT NULL,
  `korisnik_broj_prijava` INT NOT NULL,
  `tip_korisnika_idtip_korisnika` INT NOT NULL,
  PRIMARY KEY (`idkorisnik`),
  INDEX `fk_korisnik_tip_korisnika1_idx` (`tip_korisnika_idtip_korisnika` ASC) ,
  CONSTRAINT `fk_korisnik_tip_korisnika1`
    FOREIGN KEY (`tip_korisnika_idtip_korisnika`)
    REFERENCES `WebDiP2021x001`.`tip_korisnika` (`idtip_korisnika`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WebDiP2021x001`.`rang_lista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WebDiP2021x001`.`rang_lista` (
  `idrang_lista` INT NOT NULL,
  `rang_lista_od` DATE NOT NULL,
  `rang_lista_do` DATE NOT NULL,
  `rang_lista_kolicina` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idrang_lista`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WebDiP2021x001`.`popis_narudzbi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WebDiP2021x001`.`popis_narudzbi` (
  `idpopis_narudzbi` INT NOT NULL,
  `popis_narudzbi_iznos` DECIMAL NOT NULL,
  `popis_narudzbi_datum` DATETIME NOT NULL,
  `korisnik_idkorisnik` INT NOT NULL,
  PRIMARY KEY (`idpopis_narudzbi`),
  INDEX `fk_popis_narudzbi_korisnik1_idx` (`korisnik_idkorisnik` ASC) ,
  CONSTRAINT `fk_popis_narudzbi_korisnik1`
    FOREIGN KEY (`korisnik_idkorisnik`)
    REFERENCES `WebDiP2021x001`.`korisnik` (`idkorisnik`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WebDiP2021x001`.`narudzba`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WebDiP2021x001`.`narudzba` (
  `idnarudzba` INT NOT NULL,
  `narudzba_stavke` VARCHAR(45) NOT NULL,
  `narudzba_status` VARCHAR(45) NOT NULL,
  `narudzba_datum` DATETIME NOT NULL,
  `racun_idracun` INT NOT NULL,
  `korisnik_idkorisnik` INT NOT NULL,
  `rang_lista_idrang_lista` INT NOT NULL,
  `popis_narudzbi_idpopis_narudzbi` INT NOT NULL,
  PRIMARY KEY (`idnarudzba`),
  INDEX `fk_narudzba_racun1_idx` (`racun_idracun` ASC) ,
  INDEX `fk_narudzba_korisnik1_idx` (`korisnik_idkorisnik` ASC) ,
  INDEX `fk_narudzba_rang_lista1_idx` (`rang_lista_idrang_lista` ASC) ,
  INDEX `fk_narudzba_popis_narudzbi1_idx` (`popis_narudzbi_idpopis_narudzbi` ASC) ,
  CONSTRAINT `fk_narudzba_racun1`
    FOREIGN KEY (`racun_idracun`)
    REFERENCES `WebDiP2021x001`.`racun` (`idracun`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_narudzba_korisnik1`
    FOREIGN KEY (`korisnik_idkorisnik`)
    REFERENCES `WebDiP2021x001`.`korisnik` (`idkorisnik`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_narudzba_rang_lista1`
    FOREIGN KEY (`rang_lista_idrang_lista`)
    REFERENCES `WebDiP2021x001`.`rang_lista` (`idrang_lista`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_narudzba_popis_narudzbi1`
    FOREIGN KEY (`popis_narudzbi_idpopis_narudzbi`)
    REFERENCES `WebDiP2021x001`.`popis_narudzbi` (`idpopis_narudzbi`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WebDiP2021x001`.`nacin_placanja`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WebDiP2021x001`.`nacin_placanja` (
  `idnacin_placanja` INT NOT NULL,
  `nacin_placanja_naziv` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idnacin_placanja`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WebDiP2021x001`.`zemlja_podrijetla_piva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WebDiP2021x001`.`zemlja_podrijetla_piva` (
  `idzemlja_podrijetla_piva` INT NOT NULL,
  `zemlja_podrijetla_piva_naziv` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idzemlja_podrijetla_piva`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WebDiP2021x001`.`vrsta_piva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WebDiP2021x001`.`vrsta_piva` (
  `idvrsta_piva` INT NOT NULL,
  `vrsta_piva_naziv` VARCHAR(45) NOT NULL,
  `vrsta_piva_cijena` VARCHAR(45) NOT NULL,
  `vrsta_piva_rok_trajanja` DATE NOT NULL,
  `vrsta_piva_opis` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idvrsta_piva`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WebDiP2021x001`.`recepti`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WebDiP2021x001`.`recepti` (
  `idrecepti` INT NOT NULL,
  `recepti_sastojci` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idrecepti`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WebDiP2021x001`.`popis_piva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WebDiP2021x001`.`popis_piva` (
  `idpopis_piva` INT NOT NULL,
  `popis_piva_naziv_popisa` VARCHAR(45) NOT NULL,
  `zemlja_podrijetla_piva_idzemlja_podrijetla_piva` INT NOT NULL,
  `vrsta_piva_idvrsta_piva` INT NOT NULL,
  `korisnik_idkorisnik` INT NOT NULL,
  `recepti_idrecepti` INT NOT NULL,
  PRIMARY KEY (`idpopis_piva`),
  INDEX `fk_popis_piva_zemlja_podrijetla_piva1_idx` (`zemlja_podrijetla_piva_idzemlja_podrijetla_piva` ASC) ,
  INDEX `fk_popis_piva_vrsta_piva1_idx` (`vrsta_piva_idvrsta_piva` ASC) ,
  INDEX `fk_popis_piva_korisnik1_idx` (`korisnik_idkorisnik` ASC) ,
  INDEX `fk_popis_piva_recepti1_idx` (`recepti_idrecepti` ASC) ,
  CONSTRAINT `fk_popis_piva_zemlja_podrijetla_piva1`
    FOREIGN KEY (`zemlja_podrijetla_piva_idzemlja_podrijetla_piva`)
    REFERENCES `WebDiP2021x001`.`zemlja_podrijetla_piva` (`idzemlja_podrijetla_piva`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_popis_piva_vrsta_piva1`
    FOREIGN KEY (`vrsta_piva_idvrsta_piva`)
    REFERENCES `WebDiP2021x001`.`vrsta_piva` (`idvrsta_piva`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_popis_piva_korisnik1`
    FOREIGN KEY (`korisnik_idkorisnik`)
    REFERENCES `WebDiP2021x001`.`korisnik` (`idkorisnik`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_popis_piva_recepti1`
    FOREIGN KEY (`recepti_idrecepti`)
    REFERENCES `WebDiP2021x001`.`recepti` (`idrecepti`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WebDiP2021x001`.`popis_pivnica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WebDiP2021x001`.`popis_pivnica` (
  `idpopis_pivnica` INT NOT NULL,
  `popis_pivnica_naziv_popisa` VARCHAR(45) NOT NULL,
  `korisnik_idkorisnik` INT NOT NULL,
  PRIMARY KEY (`idpopis_pivnica`),
  INDEX `fk_popis_pivnica_korisnik1_idx` (`korisnik_idkorisnik` ASC) ,
  CONSTRAINT `fk_popis_pivnica_korisnik1`
    FOREIGN KEY (`korisnik_idkorisnik`)
    REFERENCES `WebDiP2021x001`.`korisnik` (`idkorisnik`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WebDiP2021x001`.`racun_has_nacin_placanja`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WebDiP2021x001`.`racun_has_nacin_placanja` (
  `racun_idracun` INT NOT NULL,
  `nacin_placanja_idnacin_placanja` INT NOT NULL,
  PRIMARY KEY (`racun_idracun`, `nacin_placanja_idnacin_placanja`),
  INDEX `fk_racun_has_nacin_placanja_nacin_placanja1_idx` (`nacin_placanja_idnacin_placanja` ASC) ,
  INDEX `fk_racun_has_nacin_placanja_racun1_idx` (`racun_idracun` ASC) ,
  CONSTRAINT `fk_racun_has_nacin_placanja_racun1`
    FOREIGN KEY (`racun_idracun`)
    REFERENCES `WebDiP2021x001`.`racun` (`idracun`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_racun_has_nacin_placanja_nacin_placanja1`
    FOREIGN KEY (`nacin_placanja_idnacin_placanja`)
    REFERENCES `WebDiP2021x001`.`nacin_placanja` (`idnacin_placanja`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WebDiP2021x001`.`popis_piva_has_popis_pivnica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WebDiP2021x001`.`popis_piva_has_popis_pivnica` (
  `popis_piva_idpopis_piva` INT NOT NULL,
  `popis_pivnica_idpopis_pivnica` INT NOT NULL,
  PRIMARY KEY (`popis_piva_idpopis_piva`, `popis_pivnica_idpopis_pivnica`),
  INDEX `fk_popis_piva_has_popis_pivnica_popis_pivnica1_idx` (`popis_pivnica_idpopis_pivnica` ASC) ,
  INDEX `fk_popis_piva_has_popis_pivnica_popis_piva1_idx` (`popis_piva_idpopis_piva` ASC) ,
  CONSTRAINT `fk_popis_piva_has_popis_pivnica_popis_piva1`
    FOREIGN KEY (`popis_piva_idpopis_piva`)
    REFERENCES `WebDiP2021x001`.`popis_piva` (`idpopis_piva`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_popis_piva_has_popis_pivnica_popis_pivnica1`
    FOREIGN KEY (`popis_pivnica_idpopis_pivnica`)
    REFERENCES `WebDiP2021x001`.`popis_pivnica` (`idpopis_pivnica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WebDiP2021x001`.`pivnica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WebDiP2021x001`.`pivnica` (
  `idpivnica` INT NOT NULL,
  `pivnica_naziv_pivnice` VARCHAR(45) NOT NULL,
  `pivnica_adresa_pivnice` VARCHAR(45) NOT NULL,
  `popis_pivnica_idpopis_pivnica` INT NOT NULL,
  PRIMARY KEY (`idpivnica`),
  INDEX `fk_pivnica_popis_pivnica1_idx` (`popis_pivnica_idpopis_pivnica` ASC) ,
  CONSTRAINT `fk_pivnica_popis_pivnica1`
    FOREIGN KEY (`popis_pivnica_idpopis_pivnica`)
    REFERENCES `WebDiP2021x001`.`popis_pivnica` (`idpopis_pivnica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
