-- MySQL Script generated by MySQL Workbench
-- Sat Apr  9 12:52:49 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`tip_korisnika`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tip_korisnika` (
  `idtip_korisnika` INT NOT NULL,
  `tip_korisnika_naziv` VARCHAR(45) NOT NULL,
  `tip_korisnika_status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idtip_korisnika`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`racun`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`racun` (
  `idracun` INT NOT NULL,
  `racun_stavke` VARCHAR(45) NOT NULL,
  `racun_iznos` VARCHAR(45) NOT NULL,
  `racun_status` TINYINT NOT NULL,
  `racun_datum` DATETIME NOT NULL,
  PRIMARY KEY (`idracun`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`korisnik`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`korisnik` (
  `idkorisnik` INT NOT NULL,
  `korisnik_ime` VARCHAR(45) NOT NULL,
  `korisnik_prezime` VARCHAR(45) NOT NULL,
  `korisnik_korisnicko_ime` VARCHAR(45) NOT NULL,
  `korisnik_lozinka` VARCHAR(45) NOT NULL,
  `korisnik_email` VARCHAR(45) NOT NULL,
  `korisnik_datum_pristupanja` DATETIME NOT NULL,
  `korisnik_datum_zabrane` DATETIME NOT NULL,
  `korisnik_datum_prihvacanja_kolacica` DATETIME NOT NULL,
  `korisnik_broj_prijava` INT NOT NULL,
  `korisnik_datum_rodenja` DATETIME NOT NULL,
  `tip_korisnika_idtip_korisnika` INT NOT NULL,
  PRIMARY KEY (`idkorisnik`),
  INDEX `fk_korisnik_tip_korisnika1_idx` (`tip_korisnika_idtip_korisnika` ASC) VISIBLE,
  CONSTRAINT `fk_korisnik_tip_korisnika1`
    FOREIGN KEY (`tip_korisnika_idtip_korisnika`)
    REFERENCES `mydb`.`tip_korisnika` (`idtip_korisnika`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`narudzba`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`narudzba` (
  `idnarudzba` INT NOT NULL,
  `narudzba_stavke` VARCHAR(45) NOT NULL,
  `narudzba_status` VARCHAR(45) NOT NULL,
  `narudzba_datum` DATETIME NOT NULL,
  `racun_idracun` INT NOT NULL,
  `korisnik_idkorisnik` INT NOT NULL,
  PRIMARY KEY (`idnarudzba`),
  INDEX `fk_narudzba_racun1_idx` (`racun_idracun` ASC) VISIBLE,
  INDEX `fk_narudzba_korisnik1_idx` (`korisnik_idkorisnik` ASC) VISIBLE,
  CONSTRAINT `fk_narudzba_racun1`
    FOREIGN KEY (`racun_idracun`)
    REFERENCES `mydb`.`racun` (`idracun`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_narudzba_korisnik1`
    FOREIGN KEY (`korisnik_idkorisnik`)
    REFERENCES `mydb`.`korisnik` (`idkorisnik`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`nacin_placanja`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`nacin_placanja` (
  `idnacin_placanja` INT NOT NULL,
  `nacin_placanja_naziv` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idnacin_placanja`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`popis_narudzbi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`popis_narudzbi` (
  `idpopis_narudzbi` INT NOT NULL,
  `popis_narudzbi_stavke` VARCHAR(45) NOT NULL,
  `popis_narudzbi_iznos` DECIMAL NOT NULL,
  `popis_narudzbi_datum` DATETIME NOT NULL,
  `korisnik_idkorisnik` INT NOT NULL,
  PRIMARY KEY (`idpopis_narudzbi`),
  INDEX `fk_popis_narudzbi_korisnik1_idx` (`korisnik_idkorisnik` ASC) VISIBLE,
  CONSTRAINT `fk_popis_narudzbi_korisnik1`
    FOREIGN KEY (`korisnik_idkorisnik`)
    REFERENCES `mydb`.`korisnik` (`idkorisnik`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`zemlja_podrijetla_piva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`zemlja_podrijetla_piva` (
  `idzemlja_podrijetla_piva` INT NOT NULL,
  `zemlja_podrijetla_piva_naziv` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idzemlja_podrijetla_piva`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`vrsta_piva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`vrsta_piva` (
  `idvrsta_piva` INT NOT NULL,
  `vrsta_piva_naziv` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idvrsta_piva`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`recepti`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`recepti` (
  `idrecepti` INT NOT NULL,
  `recepti_nacin_pripreme` VARCHAR(45) NOT NULL,
  `recepti_sastojci` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idrecepti`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`popis_piva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`popis_piva` (
  `idpopis_piva` INT NOT NULL,
  `popis_piva_naziv_piva` VARCHAR(45) NOT NULL,
  `popis_piva_kolicina` INT NOT NULL,
  `popis_piva_cijena` VARCHAR(45) NOT NULL,
  `zemlja_podrijetla_piva_idzemlja_podrijetla_piva` INT NOT NULL,
  `vrsta_piva_idvrsta_piva` INT NOT NULL,
  `korisnik_idkorisnik` INT NOT NULL,
  `recepti_idrecepti` INT NOT NULL,
  PRIMARY KEY (`idpopis_piva`),
  INDEX `fk_popis_piva_zemlja_podrijetla_piva1_idx` (`zemlja_podrijetla_piva_idzemlja_podrijetla_piva` ASC) VISIBLE,
  INDEX `fk_popis_piva_vrsta_piva1_idx` (`vrsta_piva_idvrsta_piva` ASC) VISIBLE,
  INDEX `fk_popis_piva_korisnik1_idx` (`korisnik_idkorisnik` ASC) VISIBLE,
  INDEX `fk_popis_piva_recepti1_idx` (`recepti_idrecepti` ASC) VISIBLE,
  CONSTRAINT `fk_popis_piva_zemlja_podrijetla_piva1`
    FOREIGN KEY (`zemlja_podrijetla_piva_idzemlja_podrijetla_piva`)
    REFERENCES `mydb`.`zemlja_podrijetla_piva` (`idzemlja_podrijetla_piva`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_popis_piva_vrsta_piva1`
    FOREIGN KEY (`vrsta_piva_idvrsta_piva`)
    REFERENCES `mydb`.`vrsta_piva` (`idvrsta_piva`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_popis_piva_korisnik1`
    FOREIGN KEY (`korisnik_idkorisnik`)
    REFERENCES `mydb`.`korisnik` (`idkorisnik`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_popis_piva_recepti1`
    FOREIGN KEY (`recepti_idrecepti`)
    REFERENCES `mydb`.`recepti` (`idrecepti`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`popis_pivnica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`popis_pivnica` (
  `idpopis_pivnica` INT NOT NULL,
  `popis_pivnica_naziv_pivnice` VARCHAR(45) NOT NULL,
  `popis_pivnica_adresa_pivnice` VARCHAR(45) NOT NULL,
  `korisnik_idkorisnik` INT NOT NULL,
  PRIMARY KEY (`idpopis_pivnica`),
  INDEX `fk_popis_pivnica_korisnik1_idx` (`korisnik_idkorisnik` ASC) VISIBLE,
  CONSTRAINT `fk_popis_pivnica_korisnik1`
    FOREIGN KEY (`korisnik_idkorisnik`)
    REFERENCES `mydb`.`korisnik` (`idkorisnik`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`racun_has_nacin_placanja`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`racun_has_nacin_placanja` (
  `racun_idracun` INT NOT NULL,
  `nacin_placanja_idnacin_placanja` INT NOT NULL,
  PRIMARY KEY (`racun_idracun`, `nacin_placanja_idnacin_placanja`),
  INDEX `fk_racun_has_nacin_placanja_nacin_placanja1_idx` (`nacin_placanja_idnacin_placanja` ASC) VISIBLE,
  INDEX `fk_racun_has_nacin_placanja_racun1_idx` (`racun_idracun` ASC) VISIBLE,
  CONSTRAINT `fk_racun_has_nacin_placanja_racun1`
    FOREIGN KEY (`racun_idracun`)
    REFERENCES `mydb`.`racun` (`idracun`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_racun_has_nacin_placanja_nacin_placanja1`
    FOREIGN KEY (`nacin_placanja_idnacin_placanja`)
    REFERENCES `mydb`.`nacin_placanja` (`idnacin_placanja`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`popis_piva_has_popis_pivnica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`popis_piva_has_popis_pivnica` (
  `popis_piva_idpopis_piva` INT NOT NULL,
  `popis_pivnica_idpopis_pivnica` INT NOT NULL,
  PRIMARY KEY (`popis_piva_idpopis_piva`, `popis_pivnica_idpopis_pivnica`),
  INDEX `fk_popis_piva_has_popis_pivnica_popis_pivnica1_idx` (`popis_pivnica_idpopis_pivnica` ASC) VISIBLE,
  INDEX `fk_popis_piva_has_popis_pivnica_popis_piva1_idx` (`popis_piva_idpopis_piva` ASC) VISIBLE,
  CONSTRAINT `fk_popis_piva_has_popis_pivnica_popis_piva1`
    FOREIGN KEY (`popis_piva_idpopis_piva`)
    REFERENCES `mydb`.`popis_piva` (`idpopis_piva`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_popis_piva_has_popis_pivnica_popis_pivnica1`
    FOREIGN KEY (`popis_pivnica_idpopis_pivnica`)
    REFERENCES `mydb`.`popis_pivnica` (`idpopis_pivnica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
